name: mtbnn_sinusoid1d_maml_settings 
description: |
  Test MT-BNN at Sinuosoid1D with the settings we identified at single-task 
  MT-BNN runs and multi-task MAML runs.
project: mtbnn_v0
program: run_mtbnn.py
method: grid 
parameters: 
    bm: 
      value: "Sinusoid1D"
    prior_init:
      value: "standard_normal"
    posterior_init:
      value: "set_to_prior"
    normalize_bm:
      value: True
    n_tasks_meta:
      value: 16
    n_hidden:
      value: 2
    d_hidden:
      value: 16
    seed_pyro: 
      values: [123, 223, 323]
    prior_type:
      values: ["fixed", "factorized_normal"]
    initial_lr:
      values: [1e-1, 5e-2]
    final_lr:
      values: [5e-3, 1e-5]
    
